library(devtools)
library(roxygen2)
library(dplyr)
# create("cdashQC")
setwd("C:/Users/zhuob01/Documents/cdashQC/cdashQC-master")
# 
# devtools::use_data(CODES, internal = T)
document()
check()
build(manual = T)
install.packages("~/cdashQC/cdashQC_0.1.1.tar.gz", repos = NULL, type = "source")
